CREATE TABLE stg_calidad_agua (
    fecha                     VARCHAR(50),
    anio                      VARCHAR(50),
    mes                       VARCHAR(50),
    periodo                   VARCHAR(50),
    sistema_abastecimiento    VARCHAR(50),
    nivel_almacenamiento_pct  VARCHAR(50),
    afluencias_m3s            VARCHAR(50),
    precipitacion_mm          VARCHAR(50),
    temperatura_c             VARCHAR(50),
    consumo_m3s               VARCHAR(50),
    irca                      VARCHAR(50),
    clasificacion_riesgo      VARCHAR(100),
    municipio                 VARCHAR(100),
    departamento              VARCHAR(100),
    latitud                   VARCHAR(50),
    longitud                  VARCHAR(50),
    cobertura_acueducto_pct   VARCHAR(50),
    nivel_servicio            VARCHAR(50),
    tipo_region               VARCHAR(50),
    decision_racionamiento    VARCHAR(100),
    lote_id                   INT,
    fecha_carga               DATETIME DEFAULT GETDATE()
);