CREATE TABLE dst_calidad_agua (
    fecha                     DATE          NOT NULL,
    anio                      SMALLINT,
    mes                       TINYINT,
    periodo                   VARCHAR(10),
    sistema_abastecimiento    VARCHAR(50)   NOT NULL,
    nivel_almacenamiento_pct  DECIMAL(5,2),
    afluencias_m3s            DECIMAL(8,2),
    precipitacion_mm          DECIMAL(8,2),
    temperatura_c             DECIMAL(5,2),
    consumo_m3s               DECIMAL(8,2),
    irca                      DECIMAL(5,2),
    irca_reportado            VARCHAR(2),
    clasificacion_riesgo      VARCHAR(50),
    municipio                 VARCHAR(100)  NOT NULL,
    departamento              VARCHAR(100),
    latitud                   DECIMAL(9,6),
    longitud                  DECIMAL(9,6),
    cobertura_acueducto_pct   DECIMAL(5,2),
    nivel_servicio            VARCHAR(30),
    tipo_region               VARCHAR(20),
    decision_racionamiento    VARCHAR(100),
    lote_id                   INT,
    iteracion                 INT           NOT NULL,
    fecha_carga               DATETIME      DEFAULT GETDATE(),
    CONSTRAINT UQ_dst_llave UNIQUE (iteracion, fecha, municipio, sistema_abastecimiento)
);